MTV-66: RHV cold migration
konveyor/forklift-documentation pull request #151
Opened 2021-06-15 12:09 UTC by apinnick

2021-07-22 11:10 UTC, apinnick commented on documentation/modules/migrating-virtual-machines-cli.adoc
> +        accessMode: ReadWriteOnce
@istein1  Is `ReadWriteOnce` mandatory or can the user choose other access modes?

2021-07-27 08:58 UTC, apinnick commented
@istein1 
Ready for QE review except for network ports.

2021-07-27 08:59 UTC, apinnick commented on documentation/modules/migration-environment-requirements.adoc
>  .Network ports required for migration
Need info for network ports for RHV.

2021-08-12 10:16 UTC, apinnick commented on documentation/modules/adding-source-provider.adoc
> +* *CA certificate*: CA certificate of the {manager}. You can retrieve it at `https://<www.example.com>/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA`.
Not sure it makes any difference but I can move to prerequisites and see how it looks.

2021-08-16 07:13 UTC, amastbau requested changes

2021-08-16 07:13 UTC, amastbau commented on documentation/modules/migrating-virtual-machines-cli.adoc
> +  cacert: <{rhv_short}_ca_certificate> <3>
Should be {rhv-short}

2021-08-16 07:56 UTC, amastbau requested changes

2021-08-16 07:56 UTC, amastbau commented on documentation/modules/migrating-virtual-machines-cli.adoc
> +data:
stingData not data

2021-08-22 11:56 UTC, amastbau commented
/lgtm but looks like we need final confirmation about the network port?

2021-08-22 13:10 UTC, apinnick commented
> /lgtm but looks like we need final confirmation about the network port?

@amastbau  Yes. I can ask at tomorrow's program meeting if I do not have an answer before then.

2021-08-23 14:54 UTC, merged