BZ2020300: Get logs button disabled
konveyor/forklift-documentation pull request #243
Opened 2021-11-11 09:47 UTC by apinnick

2021-11-11 15:01 UTC, apinnick commented
@mguetta1 I updated the PR. Ready for review.

2021-11-11 17:00 UTC, mguetta1 requested changes

2021-11-11 17:00 UTC, mguetta1 commented on documentation/modules/rn-2.2.adoc
> +Retaining the `Importer` pod causes warm migration to hang during the cutover stage. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2016290[*BZ#2016290*])
...during precopy stage
https://bugzilla.redhat.com/show_bug.cgi?id=2016290#c14

2021-11-11 17:00 UTC, mguetta1 commented on documentation/modules/rn-2.2.adoc
> +As a workaround, the `Importer` pod is removed at the end of the precopy stage so that the cutover stage succeeds. However, as a result, the `Importer` log is unavailable after the warm migration is
so the precopy stage succeeds

2021-11-14 09:39 UTC, mguetta1 approved these changes
LGTM

2021-11-14 09:41 UTC, merged