Add BZ#2023764 to known issues for MTV 2.2 Release notes
konveyor/forklift-documentation pull request #277
Opened 2021-12-19 16:14 UTC by RichardHoch

MTV 2.2

Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2023764#c1

2021-12-20 06:14 UTC, mguetta1 requested changes

2021-12-20 06:14 UTC, mguetta1 commented on documentation/modules/rn-2.2.adoc
> +.Log archive files downloaded from the {project-short} web console might include logs related to a deleted migration plan
1. "Log archive files" -> it is one file that includes several logs
2. Please change the end to "deleted resource" - can be deleted plan or target VM resource

2021-12-20 06:14 UTC, mguetta1 commented on documentation/modules/rn-2.2.adoc
> +If you do either of the following in the {project-short} web console, the log archive you download might contain logs related to a deleted migration plan:
1. Please remove "in the {project-short} web console" - the user can delete the resources via CLI
2. and mention that: the "log archive you download **from the {project-short} web console**
3. Please add that "Or deleted target VM" at the end

2021-12-20 06:14 UTC, mguetta1 commented on documentation/modules/rn-2.2.adoc
> +In either case, the *Get logs* button, which is used to collect the logs of a new migration, does not appear following the migration as expected. Instead, the *Download logs* button, which is used to
The attached link redirects to the first comment. could you please change it to be the bug main page?

2021-12-20 09:13 UTC, mguetta1 requested changes

2021-12-20 09:13 UTC, mguetta1 commented on documentation/modules/rn-2.2.adoc
> +In either case, the *Get logs* button, which is used to collect the logs of a new migration, does not appear following the migration as expected. Instead, the *Download logs* button, which is used to
Looks like the BZ link should be bold (compared to others)

2021-12-20 09:50 UTC, mguetta1 approved these changes
Looks good to me

2021-12-20 10:31 UTC, apinnick commented on documentation/modules/rn-2.2.adoc
> +.A log archive file downloaded from the {project-short} web console might include logs related to a deleted resource
This looks like a copy/paste directly from the bug. Please rewrite according to our style, for example, briefer title.

2021-12-20 10:32 UTC, apinnick commented on documentation/modules/rn-2.2.adoc
> +If you do either of the following, the log archive file you download from the {project-short} web console might contain logs related to a deleted migration plan or a deleted target VM:
Rewrite the first clause. "either of the following" is not clear style.

2021-12-20 10:32 UTC, apinnick commented on documentation/modules/rn-2.2.adoc
> +* Delete a migration plan and then recreate the plan using the same name
Make these two bullet points  more concise.

2021-12-20 10:33 UTC, apinnick commented on documentation/modules/rn-2.2.adoc
> +In either case, the *Get logs* button, which is used to collect the logs of a new migration, does not appear following the migration as expected. Instead, the *Download logs* button, which is used to
Avoid "in either case". Ambiguous and usually unneccessary.

2021-12-20 10:33 UTC, apinnick requested changes
Please make this known issue shorter and more concise.

2021-12-22 12:18 UTC, apinnick commented on documentation/modules/rn-2.2.adoc
> +.A downloaded log archive file might include logs from a deleted resource
Change to "Log archive file includes logs of a deleted migration plan or VM"

You don't need "might" in the header. You also don't need "downloaded". That can be explained in the description.

2021-12-22 12:23 UTC, apinnick commented on documentation/modules/rn-2.2.adoc
> +A log archive file downloaded from the {project-short} web console might include logs from a deleted resource if it was generated after you deleted a migration plan and recreated it with the same nam
Suggest this:

If you delete a migration plan and then run a new migration plan with the same name or if you delete a migrated VM and then remigrate the source VM, the log archive file created by the {project-short} web console might include the logs of the deleted migration plan or VM. [bug link]

2021-12-22 12:25 UTC, apinnick requested changes
Added comments.

2021-12-22 14:53 UTC, mguetta1 requested changes

2021-12-22 14:53 UTC, mguetta1 commented on documentation/modules/rn-2.2.adoc
> +If you delete a migration plan and then run a new migration plan with the same name or if you delete a migrated VM and then remigrate the source VM, the log archive file created by the {project-short
[bug link] should be removed

2021-12-22 15:03 UTC, mguetta1 approved these changes
Looks good to me. Thanks

2021-12-23 08:49 UTC, apinnick approved these changes

2021-12-23 08:49 UTC, merged